configName: samc21_xpro
folderName: samc21_tcc_gpio_counter
format_version: v1.0
frameworkPath: D:\Harmony3
processor: ATSAMC21J18A
projectName: samc21_tcc_gpio_counter
settings:
  PackageFilter: csp;csp_apps_sam_c20_c21;quick_docs;touch
  FORCE_OPTIMIZATION: 'false'
  GENERATE_BACKUP: 'true'
  TRUSTZONE: 'false'
  CMSISPath: .\dev_packs\arm\CMSIS\5.7.0
  MERGE_STRATEGY: USER_ALL
  DFPPath: .\dev_packs\Microchip\SAMC21_DFP\3.5.95\samc21\atdf\ATSAMC21J18A.atdf
